export const bridge = {} as any;
export const BRIDGE_TOKENS = [] as any;
export const commitmentHex = (): any => '0x0';
export const createBridgeNote = (): any => ({});
export type LightClientHead = any;
export const lockOnL1 = (): any => ({});
export const readIsBridged = (): any => Promise.resolve(false);
export const readLightClientHead = (): any => ({});
export const requestBridgeIn = (): any => ({});
export const sepoliaTxUrl = (): any => '';
export const starknetContractUrl = (): any => '';
